# After changing this file, check it on: http://lint.travis-ci.org
language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - pypy
  - pypy3
matrix:
  allow_failures:
    # PyPy3 seems to have issues since PyCountry was updated to its
    # Calendar-based versionning.
    - python: pypy3
install:
  - pip install -e .
  - pip install codecov
script:
  - coverage run setup.py test
  - coverage report -m
after_script:
  codecov
