# After changing this file, check it on: http://lint.travis-ci.org/
language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
  - pypy3

matrix:
  allow_failures:
    # Allow failure while we wait for Travis to propose a dedicated
    # Python 3.7 build target.
    - python: "3.7"

before_install:
  # Check default Python version installed.
  - python --version

before_script:
  - pip install codecov

script:
  # Launch unittests.
  - pip install -e .[tests]
  - coverage run ./setup.py test
  - coverage report -m
  # Check coding style.
  - pycodestyle
  # Test that building packages works.
  - pip install -e .[develop]
  - ./setup.py sdist bdist_egg bdist_wheel
  # Validates package metadata.
  - ./setup.py check -m -r -s

after_script:
  - codecov
